doctrine:
  dbal:
    override_url: true
    url: '%env(resolve:DATABASE_URL)%'
    charset: UTF8

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
    types:
      uuid: Ramsey\Uuid\Doctrine\UuidType
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Sik0r\TennisReservation\Domain\Entity:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/config/doctrine/mappings'
        prefix: 'Sik0r\TennisReservation\Domain\Entity'
        alias: Sik0r\TennisReservation\Domain\Entity
