framework:
  messenger:
    transports:
      sync: 'sync://'
    default_bus: command.bus
    buses:
      command.bus:
        middleware:
          - validation
          - doctrine_transaction
      query.bus:
        middleware:
          - validation
