Sik0r\TennisReservation\Application\Player\CreatePlayer\CreatePlayerCommand:
  properties:
    username:
      - Sik0r\TennisReservation\Infrastructure\Domain\Validators\Unique\UniqueEntity:
          fields: [username]
          entityClass: Sik0r\TennisReservation\Domain\Player\Player
      - NotBlank: ~
      - Length:
          min: 3
          max: 20
    email:
      - Sik0r\TennisReservation\Infrastructure\Domain\Validators\Unique\UniqueEntity:
          fields: [ email ]
          entityClass: Sik0r\TennisReservation\Domain\Player\Player
      - Email: ~
      - NotBlank: ~
      - Length:
          max: 255
    password:
      - NotBlank: ~
      - Length:
          min: 8
          max: 50
    confirmPassword:
      - EqualTo:
          propertyPath: password
