Sik0r\TennisReservation\Application\Commands\Player\CreatePlayerCommand:
  properties:
    username:
      - NotBlank: ~
      - Length:
          min: 3
          max: 20
    email:
      - Email: ~
      - NotBlank: ~
      - Length:
          max: 255
    password:
      - NotBlank: ~
      - Length:
          min: 8
          max: 50
    confirmPassword:
      - EqualTo:
          propertyPath: password
