parameters:

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    # all services implementing the CommandHandlerInterface
    # will be registered on the command.bus bus
    Sik0r\TennisReservation\Application\CommandHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: command.bus }
    # while those implementing QueryBusInterface will be
    # registered on the query.bus bus
    Sik0r\TennisReservation\Application\QueryHandlerInterface:
      tags:
        - { name: messenger.message_handler, bus: query.bus }

  Sik0r\TennisReservation\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Domain/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  Sik0r\TennisReservation\Web\Controller\:
    resource: '../src/Web/Controller/'
    tags: [ 'controller.service_arguments' ]

  Sik0r\TennisReservation\Web\Listeners\RequestDecodeListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request }

  Sik0r\TennisReservation\Web\Listeners\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
